spring:
  application:
    name: mini

server:
  port: 9071

camel:
  rest:
    port: 9081
    component: jetty
    binding-mode: json
  springboot:
    routes-include-pattern: file:yaml/mini/**/*.yaml